<script setup>
import { Head, Link, router } from '@inertiajs/vue3';
import AdminLayout from '../../Layouts/AdminLayout.vue';
import { ref } from 'vue';
const props = defineProps({ appointment: Object });
const status = ref(props.appointment.status);
const saveStatus = () => router.patch(`/admin/appointments/${props.appointment.id}/status`, { status: status.value });
</script>
<template><Head title="Appointment details" /><AdminLayout><div class="page-heading"><div><p class="eyebrow">Appointment details</p><h1>{{ appointment.appointment_no }}</h1><p>Created appointment and client information.</p></div><Link href="/admin/appointments" class="button primary">← Back to appointments</Link></div><section class="detail-grid"><article class="content-card detail-card"><p class="eyebrow">Client</p><h2>{{ appointment.client_name }}</h2><dl><div><dt>Phone</dt><dd>{{ appointment.client_phone }}</dd></div><div><dt>Email</dt><dd>{{ appointment.client_email || 'Not provided' }}</dd></div><div><dt>Message</dt><dd>{{ appointment.client_message || 'No message provided.' }}</dd></div></dl></article><article class="content-card detail-card"><p class="eyebrow">Consultation</p><h2>{{ appointment.service?.name }}</h2><dl><div><dt>Type</dt><dd>{{ appointment.consultation_type }}</dd></div><div><dt>Date</dt><dd>{{ appointment.appointment_date }}</dd></div><div><dt>Time</dt><dd>{{ appointment.start_time?.slice(0, 5) }} – {{ appointment.end_time?.slice(0, 5) }}</dd></div><div><dt>Duration</dt><dd>{{ appointment.duration }} minutes</dd></div></dl><div class="status-editor"><label>Appointment status<select v-model="status"><option value="pending">Pending</option><option value="confirmed">Confirmed / Accepted</option><option value="completed">Completed</option><option value="cancelled">Cancelled</option><option value="no_show">No show</option></select></label><button class="button primary" @click="saveStatus">Save status</button></div></article></section></AdminLayout></template>
