<script setup>
import { Head, router } from '@inertiajs/vue3';
import { reactive, ref } from 'vue';
import AdminLayout from '../../Layouts/AdminLayout.vue';

const props = defineProps({ schedules: Array });
const names = ['Sunday', 'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday'];
const rows = reactive(Object.fromEntries(props.schedules.map((schedule) => [schedule.id, { is_available: schedule.is_available, start_time: schedule.start_time?.slice(0, 5), end_time: schedule.end_time?.slice(0, 5), slot_duration: schedule.slot_duration }])));
const saving = reactive({});
const save = (schedule) => { saving[schedule.id] = true; router.put(`/admin/availability/${schedule.id}`, rows[schedule.id], { preserveScroll: true, onFinish: () => { saving[schedule.id] = false; } }); };
const adding = reactive({ day_of_week: '', is_available: true, start_time: '09:00', end_time: '17:00', slot_duration: 60 });
const showAdd = reactive({ value: false });
const missingDays = () => names.map((name, day) => ({ name, day })).filter(({ day }) => !props.schedules.some((schedule) => schedule.day_of_week === day));
const add = () => router.post('/admin/availability', adding, { preserveScroll: true, onSuccess: () => { showAdd.value = false; adding.day_of_week = ''; } });
const deleting = ref(null);
const remove = (schedule) => router.delete(`/admin/availability/${schedule.id}`, { preserveScroll: true });
</script>
<template><Head title="Availability" /><AdminLayout><div class="page-heading"><div><p class="eyebrow">Booking controls</p><h1>Availability</h1><p>Set the appointment times visitors can choose. Changes take effect on the booking form immediately.</p></div><button v-if="missingDays().length" class="button primary" @click="showAdd.value = !showAdd.value">{{ showAdd.value ? 'Close' : 'Add availability' }} <span>+</span></button></div><div v-if="showAdd.value" class="availability-add"><h2>Add a booking day</h2><div class="availability-fields"><label>Day<select v-model.number="adding.day_of_week"><option disabled value="">Select day</option><option v-for="item in missingDays()" :key="item.day" :value="item.day">{{ item.name }}</option></select></label><label>Start time<input v-model="adding.start_time" type="time"></label><label>End time<input v-model="adding.end_time" type="time"></label><label>Duration<select v-model.number="adding.slot_duration"><option :value="60">1 hour</option><option :value="90">1 hour 30 minutes</option><option :value="120">2 hours</option><option :value="180">3 hours</option></select></label></div><button class="button primary" :disabled="adding.day_of_week === ''" @click="add">Save new availability <span>→</span></button></div><div class="availability-note"><strong>How it works</strong><span>Enable a day, set working hours and choose the duration for each bookable slot.</span></div><div class="availability-list"><article v-for="schedule in schedules" :key="schedule.id" class="availability-card"><div class="availability-day"><strong>{{ names[schedule.day_of_week] }}</strong><label class="toggle"><input v-model="rows[schedule.id].is_available" type="checkbox"><span></span><em>{{ rows[schedule.id].is_available ? 'Available' : 'Unavailable' }}</em></label></div><div v-if="rows[schedule.id].is_available" class="availability-fields"><label>Start time<input v-model="rows[schedule.id].start_time" type="time"></label><label>End time<input v-model="rows[schedule.id].end_time" type="time"></label><label>Appointment duration<select v-model.number="rows[schedule.id].slot_duration"><option :value="60">1 hour</option><option :value="90">1 hour 30 minutes</option><option :value="120">2 hours</option><option :value="180">3 hours</option></select></label></div><div v-else class="unavailable-copy">Clients cannot book an appointment on this day.</div><div class="availability-actions"><button class="button primary availability-save" :disabled="saving[schedule.id]" @click="save(schedule)">{{ saving[schedule.id] ? 'Saving…' : 'Save changes' }} <span>→</span></button><template v-if="deleting === schedule.id"><span class="confirm-copy">Remove this day?</span><button class="delete-button" @click="remove(schedule)">Yes, remove</button><button class="cancel-button" @click="deleting = null">Keep</button></template><button v-else class="delete-button" @click="deleting = schedule.id">Remove</button></div></article></div></AdminLayout></template>
